# Form implementation generated from reading ui file 'WHA.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form.setEnabled(True)
        Form.resize(654, 498)
        Form.setAutoFillBackground(False)
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(100, 100, 100, 30))
        self.checkBox.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 410, 121, 51))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_2.setGeometry(QtCore.QRect(100, 150, 79, 20))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_3.setGeometry(QtCore.QRect(100, 200, 79, 20))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_4.setGeometry(QtCore.QRect(100, 250, 79, 20))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_5.setGeometry(QtCore.QRect(100, 300, 79, 20))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_6.setGeometry(QtCore.QRect(100, 350, 79, 20))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(230, 20, 411, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(100, 40, 54, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setGeometry(QtCore.QRect(310, 100, 331, 361))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(450, 80, 54, 16))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(parent=Form)
        self.radioButton.setGeometry(QtCore.QRect(200, 220, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 250, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_3.setGeometry(QtCore.QRect(200, 280, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.pushButton.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WHA"))
        self.checkBox.setText(_translate("Form", "礼包领取"))
        self.pushButton.setText(_translate("Form", "开始任务"))
        self.checkBox_2.setText(_translate("Form", "邮件领取"))
        self.checkBox_3.setText(_translate("Form", "派遣公司"))
        self.checkBox_4.setText(_translate("Form", "器者征集"))
        self.checkBox_5.setText(_translate("Form", "资源获取"))
        self.checkBox_6.setText(_translate("Form", "日常奖励"))
        self.label.setText(_translate("Form", "adb路径："))
        self.label_2.setText(_translate("Form", "运行日志"))
        self.radioButton.setText(_translate("Form", "冬谷币"))
        self.radioButton_2.setText(_translate("Form", "教材"))
        self.radioButton_3.setText(_translate("Form", "武器"))
